version: "3"

services:
  api:
    build: .
    networks:
      - blog
    restart: always
    volumes:
      - ./django_rest_framework/local_settings.py:/code/django_rest_framework/local_settings.py

networks:
  blog:


volumes:
  static: